# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:           This is Eli(e)
locale:          en_US
url:             https://eligurarie.github.io/ThisIsElie.github.io/
email:           egurarie@umd.edu

description: >- # this means to ignore newlines until "baseurl:"
  Research and teaching hub for my scattered labors. 
github_username: EliGurarie
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .Rproj.user

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Elie Gurarie"
  avatar : "/assets/images/elivodlosmall.jpg"
  email: egurarie@umd.edu
  google_scholar: d_G0tbAAAAAJ
  bio    : "University of Maryland<br>[Department of Biology](http://biology.umd.edu/)<br>College Park, MD 20472<br><br>University of Wisconsin<br>Department of Forest and Wildlife Ecology<br>Madison, WI 53706"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/EliGurarie"
    - label: "Google scholar" 
      icon: "fab ai ai-google-scholar-square"
      url: "https://scholar.google.com/citations?user=d_G0tbAAAAAJ&hl=en"
    
defaults:
  # _posts
  - scope:
      path: ""
      type: splash
    values:
      layout: splash
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar: 
        nav: "sidelinks"
    
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
